import type { Metadata } from 'next'
import { Instrument_Serif, Host_Grotesk } from 'next/font/google'
import './globals.css'
import ReactLenis from 'lenis/react'
import GsapProvider from './components/Layout/GsapProvider'
import Navigation from './components/Layout/Navigation'

const instrumentSerif = Instrument_Serif({
    variable: '--font-instrument-serif',
    weight: '400',
    style: ['normal', 'italic'],
    subsets: ['latin'],
})

const hostGrotesk = Host_Grotesk({
    variable: '--font-host-grotesk',
    weight: ['400', '800'],
    style: 'normal',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='cs'>
            <ReactLenis
                root
                options={{
                    lerp: 0.1,
                    duration: 0.8,
                    autoResize: true,
                    syncTouch: false,
                    touchMultiplier: 0,
                }}
            >
                <GsapProvider>
                    <body
                        className={`${hostGrotesk.variable} ${instrumentSerif.className} antialiased min-h-20 px-8 pt-12`}
                    >
                        <Navigation />
                        {children}
                    </body>
                </GsapProvider>
            </ReactLenis>
        </html>
    )
}
